services:
  postgres:
    image: postgres:latest
    container_name: news_service
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: news_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: